services:
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app
      - ./frontend/output:/output
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=true
      - FLASK_APP=app.py
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob
      - "10001:10001"  # Queue
      - "10002:10002"  # Table
